### ISSUE TITLE
Can't Disable Warning System?

### ISSUE THREAD

**Issue by ghost** [Shortninja66/StaffPlus#18]
Hello, I am using your plugin and want to use another plugin(LiteBans) for warning players.  This is my config:  [http://pastebin.com/ZAn5kABT](url)
As you can see under warnings it is not enabled.  Any way I can fix this?

**Comment by Shortninja66** [comment]
to _completely_ disable the warnings system, set the warnings command to blank. the current configuration would disable the act of warning and etc.

i updated the file for you [here ](http://pastebin.com/tTzaiMae)if you don't want to do it yourself since it's annoying to explain right away. basically, all you need to do is set the value for the node "commands.warn" to "" (instead of "warn").

**Comment by Shortninja66** [comment]
also, reviewing your configuration file, you do not need to include capital variants in your blacklist. if you enter "(dot)" as a registered period, it will not be case sensitive (so it detects "(dOT)", "(DoT)", etc.).

if this feature does not work as i described, then please tell me and it will be fixed right away!
