### ISSUE TITLE
Excessive Velocity set detected

### ISSUE THREAD

**Issue by AaronL98** [Shortninja66/StaffPlus#28]
I recently noticed this error pop up in console whenever a staff member uses the launcher/compass.
http://pastebin.com/raw/WvNsVdGE

I'm unsure if this is a known issue however it is resulting in a lot of console spam.

The launcher itself still works.
I'm using PaperSpigot 1.8.8

**Comment by Shortninja66** [comment]
paperspigot is not supported. also, if you have any anti-cheat, it may be contributing to this problem.

the reason why this error occurs is because some plugin, or server jar, has put restraint on the maximum velocity during move events. using the compass gadget uses velocity, so that feature is where it is occurring.
