### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by ghost** [Shortninja66/StaffPlus#3]
I've tried fixing this myself, and tried many differant texturepacks but there always seems to be the same character in front of the »'s http://prntscr.com/btrtop

**Comment by Shortninja66** [comment]
This occurs when a UTF-8 character is used in a non-UTF-8 text file. The only thing that can fix this is converting the file to UTF-8 (and replacing the invalid characters), or just replacing your current lang file with a new one (all files included in the plugin are converted to UTF-8).

Texture packs won't fix this and it's not due to my side
