### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by MichaelMBrown** [Shortninja66/StaffPlus#8]
When trying to toggle alerts, I get "An internal error occurred while attempting to preform this command"

**Comment by Shortninja66** [comment]
i can't help you if you don't send me the error.

**Comment by Shortninja66** [comment]
for one, i do not recommend using plugman. it can be the cause of many errors and can create trouble for developers because of false positive errors.

anyways, i will make sure this bug will not be able to happen in the next patch, even though it probably happened due to you loading/unloading with plugman.
